function antennapat2(X2Y2,lambda,ccoef,usu,mult1,anglemult1,mult2,anglemult2,mult3,anglemult3,mult4,anglemult4,mult5,anglemult5,mult6,anglemult6,active)

    ccoef
    %X2Y2=fliplr(X2Y2);
    step1=1;
    pat=[];
    avgx=sum(X2Y2(:,1))/length(X2Y2(:,1)); 
    avgy=sum(X2Y2(:,2))/length(X2Y2(:,2));
    rvect(:,1)=X2Y2(:,1)-avgx;
    rvect(:,2)=X2Y2(:,2)-avgy;
    rvect
    theta1=0:step1:360-step1;
    for theta=theta1;
    kvect=[-sin(theta/180*pi)  -cos(theta/180*pi)];
      for tt=1:usu,
         EbAP(tt)=exp(-j*2*pi/lambda*dot(kvect,rvect(tt,:)))*sum(ccoef(tt,:));
      end
      pat=[pat abs(sum(EbAP))];
   end
   pat=pat/(max(pat));
    %pat
    %figure
    polar(theta1/180*pi,pat);
    hold on
%    if ~isempty(find(active==1))
%      for tt=1:length(mult1(1,:)),
%       polar([anglemult1(ceil(usu(1)/2),tt)*pi/180 ...
%         anglemult1(ceil(usu(1)/2),tt)*pi/180 ...
%         anglemult1(ceil(usu(1)/2),tt)*pi/180-2*pi/180 ...
%         anglemult1(ceil(usu(1)/2),tt)*pi/180 ...
%         anglemult1(ceil(usu(1)/2),tt)*pi/180+2*pi/180],[max(pat) ...
%         max(pat)-max(pat)/6 max(pat)-max(pat)/10 max(pat)-max(pat)/6 ...
%         max(pat)-max(pat)/10],'m')  
%      end
%    end
%    if ~isempty(find(active==2))
%      for tt=1:length(mult2(1,:)),  
%       polar([anglemult2(ceil(usu(1)/2),tt)*pi/180 ...
%         anglemult2(ceil(usu(1)/2),tt)*pi/180 ...
%         anglemult2(ceil(usu(1)/2),tt)*pi/180-2*pi/180 ...
%         anglemult2(ceil(usu(1)/2),tt)*pi/180 ...
%         anglemult2(ceil(usu(1)/2),tt)*pi/180+2*pi/180],[max(pat) ...
%         max(pat)-max(pat)/6 max(pat)-max(pat)/10 max(pat)-max(pat)/6 ...
%         max(pat)-max(pat)/10],'c')
%      end
%    end 
%    if ~isempty(find(active==3))
%      for tt=1:length(mult3(1,:)),  
%       polar([anglemult3(ceil(usu(1)/2),tt)*pi/180 ...
%         anglemult3(ceil(usu(1)/2),tt)*pi/180 ...
%         anglemult3(ceil(usu(1)/2),tt)*pi/180-2*pi/180 ...
%         anglemult3(ceil(usu(1)/2),tt)*pi/180 ...
%         anglemult3(ceil(usu(1)/2),tt)*pi/180+2*pi/180],[max(pat) ...
%         max(pat)-max(pat)/6 max(pat)-max(pat)/10 max(pat)-max(pat)/6 ...
%         max(pat)-max(pat)/10],'g')
%      end
%    end
%    if ~isempty(find(active==4))
%      for tt=1:length(mult4(1,:)),  
%       polar([anglemult4(ceil(usu(1)/2),tt)*pi/180 ...
%         anglemult4(ceil(usu(1)/2),tt)*pi/180 ...
%         anglemult4(ceil(usu(1)/2),tt)*pi/180-2*pi/180 ...
%         anglemult4(ceil(usu(1)/2),tt)*pi/180 ...
%         anglemult4(ceil(usu(1)/2),tt)*pi/180+2*pi/180],[max(pat) ...
%         max(pat)-max(pat)/6 max(pat)-max(pat)/10 max(pat)-max(pat)/6 ...
%         max(pat)-max(pat)/10],'b')
%      end
%    end
%    if ~isempty(find(active==5))
%      for tt=1:length(mult5(1,:)),  
%       polar([anglemult5(ceil(usu(1)/2),tt)*pi/180 ...
%         anglemult5(ceil(usu(1)/2),tt)*pi/180 ...
%         anglemult5(ceil(usu(1)/2),tt)*pi/180-2*pi/180 ...
%         anglemult5(ceil(usu(1)/2),tt)*pi/180 ...
%         anglemult5(ceil(usu(1)/2),tt)*pi/180+2*pi/180],[max(pat) ...
%         max(pat)-max(pat)/6 max(pat)-max(pat)/10 max(pat)-max(pat)/6 ...
%         max(pat)-max(pat)/10],'k')
%      end
%    end
%    if ~isempty(find(active==6))
%      for tt=1:length(mult6(1,:)),  
%       polar([anglemult6(ceil(usu(1)/2),tt)*pi/180 ...
%         anglemult6(ceil(usu(1)/2),tt)*pi/180 ...
%         anglemult6(ceil(usu(1)/2),tt)*pi/180-2*pi/180 ...
%         anglemult6(ceil(usu(1)/2),tt)*pi/180 ...
%         anglemult6(ceil(usu(1)/2),tt)*pi/180+2*pi/180],[max(pat) ...
%         max(pat)-max(pat)/6 max(pat)-max(pat)/10 max(pat)-max(pat)/6 ...
%         max(pat)-max(pat)/10],'y')
%      end
%    end
    
    hold off
    return