function fig = vmpsrunoptions()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load vmpsrunoptions

h0 = figure('Color',[0.3 0.3 1], ...
	'Colormap',mat0, ...
	'Name','VMPS Run Options', ...
	'NumberTitle','off', ...
	'PointerShapeCData',mat1, ...
   'Position',[312 97 619 89], ...
   'HandleVisibility','callback', ...
	'Tag','Fig1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[11.25 33.75 90 15], ...
	'String',['Spatial Signatures';'Narrowband Signals';'Wideband BER      '], ...
	'Style','popupmenu', ...
	'Tag','run_option', ...
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.3 0.3 1], ...
	'FontWeight','bold', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[11.25 48.75 90 11.25], ...
	'String','Select Option', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','vmpsproc01(''select_output_file'');', ...
	'ListboxTop',0, ...
	'Position',[108.75 33.75 45 15], ...
	'String','Output file', ...
	'Tag','select_ouput_file');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'HorizontalAlignment','left', ...
	'ListboxTop',0, ...
	'Position',[156.75 35.25 292.5 15], ...
	'String','None Specified', ...
	'Style','edit', ...
	'Tag','vmps_output_file');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','vmpsproc01(''run'');', ...
	'ListboxTop',0, ...
	'Position',[405 11.25 45 15], ...
	'String','Run', ...
	'Tag','run_selected_option');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.3 0.3 1], ...
	'FontWeight','bold', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[11.25 11.25 45 11.25], ...
	'String','Duration', ...
	'Style','text', ...
	'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[56.25 11.25 45 15], ...
	'Style','edit', ...
	'Tag','vmps_duration_s');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.3 0.3 1], ...
	'FontWeight','bold', ...
	'ForegroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[101.25 11.25 45 11.25], ...
	'String','seconds', ...
	'Style','text', ...
	'Tag','StaticText1');
if nargout > 0, fig = h0; end
