% writepar

eval(['save ',p21,f21,' receiver_x0 receiver_y0 receiver_dir receiver_vel',...
' rx_el_on rx_el_x rx_el_y rx_el1_file rx_el2_file rx_el3_file rx_el4_file',...
' tx_on tx_x0 tx_y0 tx_dir tx_vel tx_mpmodel tx_scatterers tx_tmax',...
' tx_Gamma_H tx_Gamma_V tx_los tx_pat1 tx_pat2 tx_pat3 tx_pat4 -mat']);

